/* Generated by tools/make-answers.py from testdata/answers.json. Do not edit by hand.
 *
 * The same corpus the Python suites read: answers a session refuses without moving,
 * and answers it takes, so that refusing everything cannot pass. */

#ifndef AAMIO_ANSWERS_H
#define AAMIO_ANSWERS_H

/* The session every answer is fed to. */
#define CORPUS_AFTER       40L
#define CORPUS_MORE        1
#define CORPUS_LEFT_UNREAD 7L
#define CORPUS_LEFT_BYTES  70000L

typedef struct {
    const char *what;
    const char *answer;
} corpus_refused;

typedef struct {
    const char *what;
    const char *answer;
    int messages;
    long after;
} corpus_taken;

static const corpus_refused CORPUS_REFUSED[] = {
    { "a bare word where a value belongs",
      "{\"exists\":true,\"messages\":[garbage],\"next\":41}" },
    { "an escape that is not JSON's",
      "{\"exists\":true,\"messages\":[],\"next\":41,\"x\":\"\\q\"}" },
    { "a unicode escape without its four hex digits",
      "{\"exists\":true,\"messages\":[],\"next\":41,\"x\":\"\\u00zz\"}" },
    { "a unicode escape cut off by the end of the string",
      "{\"exists\":true,\"messages\":[],\"next\":41,\"x\":\"\\u00\"}" },
    { "a control character in the raw inside a string",
      "{\"exists\":true,\"messages\":[],\"next\":41,\"x\":\"tab\there\"}" },
    { "a string that never closes",
      "{\"exists\":true,\"messages\":[],\"next\":41,\"x\":\"open" },
    { "a cursor with a leading zero",
      "{\"exists\":true,\"messages\":[],\"next\":041}" },
    { "a cursor with a leading plus",
      "{\"exists\":true,\"messages\":[],\"next\":+41}" },
    { "a cursor with a point and nothing after it",
      "{\"exists\":true,\"messages\":[],\"next\":41.}" },
    { "a cursor in exponent form",
      "{\"exists\":true,\"messages\":[],\"next\":1e3}" },
    { "a cursor with a fraction",
      "{\"exists\":true,\"messages\":[],\"next\":4.5}" },
    { "a literal that is nearly one",
      "{\"exists\":tru,\"messages\":[],\"next\":41}" },
    { "a literal in capitals",
      "{\"exists\":True,\"messages\":[],\"next\":41}" },
    { "a number where a name belongs",
      "{\"exists\":true,41:[],\"next\":41}" },
    { "a string with no name before it",
      "{\"exists\":true,\"messages\":[],\"next\":41,\"stray\"}" },
    { "nested deeper than any answer goes",
      "{\"exists\":true,\"messages\":[],\"next\":41,\"x\":[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]}" },
    { "a message that is null",
      "{\"exists\":true,\"messages\":[null],\"next\":41}" },
    { "a message that is a number",
      "{\"exists\":true,\"messages\":[7],\"next\":41}" },
    { "a message that is a string",
      "{\"exists\":true,\"messages\":[\"text\"],\"next\":41}" },
    { "a message that is a list",
      "{\"exists\":true,\"messages\":[[]],\"next\":41}" },
    { "a message with nothing in it",
      "{\"exists\":true,\"messages\":[{}],\"next\":41}" },
    { "a message whose seq is a string",
      "{\"exists\":true,\"messages\":[{\"seq\":\"41\",\"body\":\"x\"}],\"next\":41}" },
    { "a message whose seq counts backwards",
      "{\"exists\":true,\"messages\":[{\"seq\":-41,\"body\":\"x\"}],\"next\":41}" },
    { "a message with no seq",
      "{\"exists\":true,\"messages\":[{\"body\":\"x\"}],\"next\":41}" },
    { "a message with no body",
      "{\"exists\":true,\"messages\":[{\"seq\":41}],\"next\":41}" },
    { "a message whose body is not text",
      "{\"exists\":true,\"messages\":[{\"seq\":41,\"body\":7}],\"next\":41}" },
    { "one message that is one and one that is not: nothing is taken",
      "{\"exists\":true,\"messages\":[{\"seq\":41,\"body\":\"x\"},null],\"next\":41}" },
    { "a reset that is false",
      "{\"exists\":true,\"messages\":[],\"next\":2,\"reset\":false}" },
    { "a reset that is true",
      "{\"exists\":true,\"messages\":[],\"next\":2,\"reset\":true}" },
    { "a reset that is an empty object",
      "{\"exists\":true,\"messages\":[],\"next\":2,\"reset\":{}}" },
    { "a reset whose after is a string",
      "{\"exists\":true,\"messages\":[],\"next\":2,\"reset\":{\"after\":\"40\",\"newest\":1}}" },
    { "a reset with no newest",
      "{\"exists\":true,\"messages\":[],\"next\":2,\"reset\":{\"after\":40}}" },
    { "more that is null",
      "{\"exists\":true,\"messages\":[],\"next\":41,\"more\":null}" },
    { "a too_large whose bytes is a string",
      "{\"exists\":true,\"messages\":[],\"next\":40,\"too_large\":{\"seq\":41,\"bytes\":\"70000\"}}" },
    { "a too_large whose bytes counts backwards",
      "{\"exists\":true,\"messages\":[],\"next\":40,\"too_large\":{\"seq\":41,\"bytes\":-1}}" },
};

static const corpus_taken CORPUS_TAKEN[] = {
    { "a plain answer, with the fields the service sends around the messages",
      "{\"w\":\"ohcibx4t22xc6hx22fch\",\"exists\":true,\"created_at\":1,\"expire_at\":2,\"count\":5,\"allow\":[],\"messages\":[],\"next\":41,\"waited\":0}", 0, 41L },
    { "one message with every field, and space before a comma",
      "{\"exists\":true,\"messages\":[{\"seq\":41,\"at\":1800000010,\"type\":\"json\",\"body\":\"{\\\"t\\\":21.4}\",\"sha256\":\"0000000000000000000000000000000000000000000000000000000000000000\",\"from\":null,\"sig\":null,\"verified\":false,\"sealed\":false}] ,\"next\":41}", 1, 41L },
    { "two messages, with the escapes JSON allows in a body",
      "{\"exists\":true,\"messages\":[{\"seq\":41,\"body\":\"a\\\\b\\/c\\n\\u00e9\"},{\"seq\":42,\"body\":\"\"}],\"next\":42}", 2, 42L },
    { "a reset in its documented shape hands back a lower cursor",
      "{\"exists\":true,\"messages\":[{\"seq\":1,\"body\":\"new\"}],\"next\":1,\"reset\":{\"after\":40,\"newest\":1,\"what\":\"the cursor belongs to an earlier thread\"}}", 1, 1L },
    { "a lower cursor without a reset is not followed",
      "{\"exists\":true,\"messages\":[],\"next\":2}", 0, 40L },
    { "nested as deep as an answer may go",
      "{\"exists\":true,\"messages\":[],\"next\":41,\"x\":[[[[[[[[[[[[[[[[[[[[[[[[[[[[[]]]]]]]]]]]]]]]]]]]]]]]]]]]]]}", 0, 41L },
    { "a note, and whitespace of every kind between the tokens",
      "{\r\n\t\"exists\" : true ,\n \"messages\" : [ ] ,\n \"next\" : 41 ,\n \"note\" : \"x\"\n}\n", 0, 41L },
};

#endif /* AAMIO_ANSWERS_H */
