/* Generated by tools/make-vectors.py from testdata/vectors.json. Do not edit by hand.
 *
 * The same file six of the seven aamio clients carry byte for byte, so a client that
 * passes these opens the envelopes the others write. sha256 of the source, with line
 * endings normalised: 342ea40158c7caa9c140fd04a83416acd754e2d5fd3d3f75b0c39d49b1783cd4
 */

#ifndef AAMIO_VECTORS_H
#define AAMIO_VECTORS_H

#define V_SHA256_ABC      "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"
#define V_ID              "abcdefghijklmnopqrstuvwxyz"
#define V_W               "ohcibx4t22xc6hx22fch"
#define V_BODY            "{\"hello\":\"from python\"}"
#define V_SIGN_INPUT      "aamio-v1\nohcibx4t22xc6hx22fch\n41749a11c112ecb7ef992a02abf17b934b6bfec8b9748ea852614c930a68bcae"
#define V_SIGNATURE       "u327kMqo4_mMzm__Wr7BrXcO4cHvx30IWw1K0cTpfTV6ODV4BFC9E0VkN3LlUvx--wFwe2J8kgSWugKXvwL8Dg"
#define V_A_PUBLIC        "A6EHv_POEL4dcN0Y50vAmWfk1jCbpQ1fHdyGZBJVMbg"
#define V_A_HASH          "56475aa75463474c0285df5dbf2bcab73da651358839e9b77481b2eab107708c"
#define V_B_PUBLIC        "ebVWLo_mVPlAeLES6KmLp5AfhTrmlb7X4OORC60ElmQ"
#define V_SCOPE_KEY       "aamioscopevector0000000000"
#define V_SCOPE_ADDRESS   "2o3wek6doqhqatib63vj"
#define V_SCOPE_AS_THREAD "ysmkpshwyvliz4muxuri"
#define V_STRAY_SIGNATURE "u327kMqo4_mMzm__Wr7BrXcO4cHvx30IWw1K0cTpfTV6ODV4BFC9E0VkN3LlUvx--wFwe2J8kgSWugKXvwL8Dh"
#define V_STRAY_KEY       "A6EHv_POEL4dcN0Y50vAmWfk1jCbpQ1fHdyGZBJVMbh"

#endif /* AAMIO_VECTORS_H */
