"""Turn the answer corpus into a C header, so the C suite reads the same cases as the Python ones.

testdata/answers.json holds answers a read session must refuse without moving, and a
few it must take, so that refusing everything cannot pass. The Python suites read the
file; the C suite has no JSON parser to read it with, so this writes test/answers.h.
One corpus rather than two: the health check of 21 September 2026 found the C and
MicroPython taking answers CPython refused, and a case that is only in one suite is a
difference nobody is told about.

    python tools/make-answers.py          # print it
    python tools/make-answers.py --write  # update test/answers.h
"""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SOURCE = os.path.join(ROOT, "testdata", "answers.json")
TARGET = os.path.join(ROOT, "test", "answers.h")


def c_string(text):
    out = []

    for character in text:
        if character == '"':
            out.append('\\"')
        elif character == "\\":
            out.append("\\\\")
        elif character == "\n":
            out.append("\\n")
        elif character == "\r":
            out.append("\\r")
        elif character == "\t":
            out.append("\\t")
        elif " " <= character <= "~":
            out.append(character)
        else:
            raise SystemExit("an answer carries a byte this generator will not guess at: %r" % character)

    return '"' + "".join(out) + '"'


def main():
    with open(SOURCE, encoding="utf-8") as handle:
        corpus = json.load(handle)

    before = corpus["before"]
    lines = [
        "/* Generated by tools/make-answers.py from testdata/answers.json. Do not edit by hand.",
        " *",
        " * The same corpus the Python suites read: answers a session refuses without moving,",
        " * and answers it takes, so that refusing everything cannot pass. */",
        "",
        "#ifndef AAMIO_ANSWERS_H",
        "#define AAMIO_ANSWERS_H",
        "",
        "/* The session every answer is fed to. */",
        "#define CORPUS_AFTER       %dL" % before["after"],
        "#define CORPUS_MORE        %d" % (1 if before["more"] else 0),
        "#define CORPUS_LEFT_UNREAD %dL" % before["left_unread"],
        "#define CORPUS_LEFT_BYTES  %dL" % before["left_bytes"],
        "",
        "typedef struct {",
        "    const char *what;",
        "    const char *answer;",
        "} corpus_refused;",
        "",
        "typedef struct {",
        "    const char *what;",
        "    const char *answer;",
        "    int messages;",
        "    long after;",
        "} corpus_taken;",
        "",
        "static const corpus_refused CORPUS_REFUSED[] = {",
    ]

    for entry in corpus["refused"]:
        lines.append("    { %s,\n      %s }," % (c_string(entry["what"]), c_string(entry["answer"])))

    lines += [
        "};",
        "",
        "static const corpus_taken CORPUS_TAKEN[] = {",
    ]

    for entry in corpus["taken"]:
        lines.append("    { %s,\n      %s, %d, %dL },"
                     % (c_string(entry["what"]), c_string(entry["answer"]), entry["messages"], entry["after"]))

    lines += [
        "};",
        "",
        "#endif /* AAMIO_ANSWERS_H */",
        "",
    ]
    text = "\n".join(lines)

    if "--write" in sys.argv:
        with open(TARGET, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)

        print("wrote %s" % TARGET)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
