"""Turn the shared vectors into a C header, so the conformance test needs no JSON parser.

The values come from testdata/vectors.json, which is the same file six of the seven clients
carry byte for byte. Generating rather than typing is the point: a number typed into a test is
a number that can disagree with the others without anyone noticing.

    python tools/make-vectors.py          # print it
    python tools/make-vectors.py --write  # update test/vectors.h
"""

import hashlib
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SOURCE = os.path.join(ROOT, "testdata", "vectors.json")
TARGET = os.path.join(ROOT, "test", "vectors.h")


def c_string(text):
    out = []

    for character in text:
        if character == '"':
            out.append('\\"')
        elif character == "\\":
            out.append("\\\\")
        elif character == "\n":
            out.append("\\n")
        elif " " <= character <= "~":
            out.append(character)
        else:
            raise SystemExit("a vector carries a byte this generator will not guess at: %r" % character)

    return '"' + "".join(out) + '"'


def main():
    raw = open(SOURCE, "rb").read()
    vectors = json.loads(raw.decode("utf-8"))
    digest = hashlib.sha256(raw.replace(b"\r\n", b"\n")).hexdigest()

    lines = [
        "/* Generated by tools/make-vectors.py from testdata/vectors.json. Do not edit by hand.",
        " *",
        " * The same file six of the seven aamio clients carry byte for byte, so a client that",
        " * passes these opens the envelopes the others write. sha256 of the source, with line",
        " * endings normalised: %s" % digest,
        " */",
        "",
        "#ifndef AAMIO_VECTORS_H",
        "#define AAMIO_VECTORS_H",
        "",
        "#define V_SHA256_ABC      %s" % c_string(vectors["sha256_abc"]),
        "#define V_ID              %s" % c_string(vectors["id"]),
        "#define V_W               %s" % c_string(vectors["w"]),
        "#define V_BODY            %s" % c_string(vectors["body"]),
        "#define V_SIGN_INPUT      %s" % c_string(vectors["signInput"]),
        "#define V_SIGNATURE       %s" % c_string(vectors["signature"]),
        "#define V_A_PUBLIC        %s" % c_string(vectors["a"]["public"]),
        "#define V_A_HASH          %s" % c_string(vectors["a"]["hash"]),
        "#define V_B_PUBLIC        %s" % c_string(vectors["b"]["public"]),
        "#define V_SCOPE_KEY       %s" % c_string(vectors["scope"]["key"]),
        "#define V_SCOPE_ADDRESS   %s" % c_string(vectors["scope"]["address"]),
        "#define V_SCOPE_AS_THREAD %s" % c_string(vectors["scope"]["thread_w_of_the_same_string"]),
        "#define V_STRAY_SIGNATURE %s" % c_string(vectors["strayBits"]["signature"]),
        "#define V_STRAY_KEY       %s" % c_string(vectors["strayBits"]["key"]),
        "",
        "#endif /* AAMIO_VECTORS_H */",
        "",
    ]
    text = "\n".join(lines)

    if "--write" in sys.argv:
        with open(TARGET, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(text)

        print("wrote %s" % TARGET)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
